#!/bin/sh
set -e

[ -f /app/update.bin ] && rm /app/update.bin
[ ${#SPEEDER_PAD_PWD} -eq 0 ] && export SPEEDER_PAD_PWD=flsun
SPEEDER_PAD_PWD=`echo $SPEEDER_PAD_PWD | sed 's/ *$//g'`

sed "s/SPEEDER_PAD_PWD/${SPEEDER_PAD_PWD}/g" update.tpl > update.sh

zip update.zip update.sh
sed -i "s/\x50\x4B\x01\x02/c604/g" update.zip
sed -i "s/\x50\x4B\x05\x06/4d19/g" update.zip
sed -i "s/\x50\x4B\x03\x04/5cc5/g" update.zip
tar -zcf update.bin update.zip
sed -i "s/\x00\x00\x00\x00\x00\x00/zzcat/g" update.bin
mv update.bin /app/update.bin

echo "Done, put the update.bin file to your USB key"
echo "start the Speeder Pad, it will process the update and reboot"
